### PR TITLE
champion card styling and server updates to allow champion splash art…

### PR DESCRIPTION
**Pull request by kbanze14**
Hello Kevin, it is I Kevin. This PR is created with intent to be a juicer. TY.

### CODE REVIEW

**Comment by kwsullivan** [comment]
Wow Kevin. Dare I say this is yet again another absolute juicer. Big dub p.

**Comment by kbanze14** [comment]
> Wow Kevin. Dare I say this is yet again another absolute juicer. Big dub p.

Enormous TY Kev

**Review by kwsullivan — APPROVED** [review]
Wow Kevin. Dare I say this is yet again another absolute juicer. Big dub p.

**Comment by kbanze14** [comment]
> Wow Kevin. Dare I say this is yet again another absolute juicer. Big dub p.

Yet again, an even more enormous TY

**Pull request merged**
